InsuranceSystemProject/Models/PolicyProperty.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceSystemProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolicyProperty
    {
        public int Id { get; set; }
        public int InsuranceValue { get; set; }
        public int City { get; set; }
        public System.DateTime PolicyStartDate { get; set; }
        public string UserId { get; set; }
        public int PersonId { get; set; }
        public int CompanyId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual City City1 { get; set; }
        public virtual InsuranceCompany InsuranceCompany { get; set; }
        public virtual PersonDetail PersonDetail { get; set; }
    }
}

InsuranceSystemProject/Controllers/PolicyPropertyController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using InsuranceSystemProject.Models;

namespace InsuranceSystemProject.Controllers
{
    public class PolicyPropertyController : Controller
    {
        private Entities1 db = new Entities1();

        // GET: PolicyProperty/PolicyPropertyIndex
        public ActionResult PolicyPropertyIndex(string searchby, string search)
        {
            var policyProperty = db.PolicyProperties.Include(p => p.AspNetUser).Include(p => p.City1).Include(p => p.InsuranceCompany).Include(p => p.PersonDetail);
            if (searchby == "Id")
            {
                int id = Int32.Parse(search);
                return View(db.PolicyProperties.Where(x => x.Id == id).ToList());
            }
            else if (searchby == "Client")
            {

                return View(db.PolicyProperties.Where(x => x.PersonDetail.FirstName == search).ToList());
            }
            else if (searchby == "Insurer")
            {

                return View(db.PolicyProperties.Where(x => x.UserId == search).ToList());
            }
            else
            {
                return View(policyProperty.ToList());
            }
        }

        /*
        // GET: PolicyProperty/PolicyPropertyDetails/5
        public ActionResult PolicyPropertyDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PolicyProperty policyProperty = db.PolicyProperties.Find(id);
            if (policyProperty == null)
            {
                return HttpNotFound();
            }
            return View(policyProperty);
        }
        */

        // GET: PolicyProperty/PolicyPropertyCreate
        public ActionResult PolicyPropertyCreate()
        {
            ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "Email");
            ViewBag.City = new SelectList(db.Cities, "Id", "CityName");
            ViewBag.CompanyId = new SelectList(db.InsuranceCompanies, "Id", "Name");
            ViewBag.PersonId = new SelectList(db.PersonDetails, "Id", "FirstName");
            return View();
        }

        // POST: PolicyProperty/PolicyPropertyCreate
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PolicyPropertyCreate([Bind(Include = "Id,InsuranceValue,City,PolicyStartDate,UserId,PersonId,CompanyId,AspNetUser,City1,InsuranceCompany,PersonDetail")] PolicyProperty policyProperty)
        {
            if (ModelState.IsValid)
            {
                db.PolicyProperties.Add(policyProperty);
                db.SaveChanges();
                DisplaySuccessMessage("Has append a PolicyProperty record");
                return RedirectToAction("PolicyPropertyIndex");
            }

            ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "Email", policyProperty.UserId);
            ViewBag.City = new SelectList(db.Cities, "Id", "CityName", policyProperty.City);
            ViewBag.CompanyId = new SelectList(db.InsuranceCompanies, "Id", "Name", policyProperty.CompanyId);
            ViewBag.PersonId = new SelectList(db.PersonDetails, "Id", "FirstName", policyProperty.PersonId);
            DisplayErrorMessage();
            return View(policyProperty);
        }

        // GET: PolicyProperty/PolicyPropertyEdit/5
        public ActionResult PolicyPropertyEdit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PolicyProperty policyProperty = db.PolicyProperties.Find(id);
            if (policyProperty == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "Email", policyProperty.UserId);
            ViewBag.City = new SelectList(db.Cities, "Id", "CityName", policyProperty.City);
            ViewBag.CompanyId = new SelectList(db.InsuranceCompanies, "Id", "Name", policyProperty.CompanyId);
            ViewBag.PersonId = new SelectList(db.PersonDetails, "Id", "FirstName", policyProperty.PersonId);
            return View(policyProperty);
        }

        // POST: PolicyPropertyPolicyProperty/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PolicyPropertyEdit([Bind(Include = "Id,InsuranceValue,City,PolicyStartDate,UserId,PersonId,CompanyId,AspNetUser,City1,InsuranceCompany,PersonDetail")] PolicyProperty policyProperty)
        {
            if (ModelState.IsValid)
            {
                db.Entry(policyProperty).State = EntityState.Modified;
                db.SaveChanges();
                DisplaySuccessMessage("Has update a PolicyProperty record");
                return RedirectToAction("PolicyPropertyIndex");
            }
            ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "Email", policyProperty.UserId);
            ViewBag.City = new SelectList(db.Cities, "Id", "CityName", policyProperty.City);
            ViewBag.CompanyId = new SelectList(db.InsuranceCompanies, "Id", "Name", policyProperty.CompanyId);
            ViewBag.PersonId = new SelectList(db.PersonDetails, "Id", "FirstName", policyProperty.PersonId);
            DisplayErrorMessage();
            return View(policyProperty);
        }

        // GET: PolicyProperty/PolicyPropertyDelete/5
        public ActionResult PolicyPropertyDelete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PolicyProperty policyProperty = db.PolicyProperties.Find(id);
            if (policyProperty == null)
            {
                return HttpNotFound();
            }
            return View(policyProperty);
        }

        // POST: PolicyProperty/PolicyPropertyDelete/5
        [HttpPost, ActionName("PolicyPropertyDelete")]
        [ValidateAntiForgeryToken]
        public ActionResult PolicyPropertyDeleteConfirmed(int id)
        {
            PolicyProperty policyProperty = db.PolicyProperties.Find(id);
            db.PolicyProperties.Remove(policyProperty);
            db.SaveChanges();
            DisplaySuccessMessage("Has delete a PolicyProperty record");
            return RedirectToAction("PolicyPropertyIndex");
        }

        private void DisplaySuccessMessage(string msgText)
        {
            TempData["SuccessMessage"] = msgText;
        }

        private void DisplayErrorMessage()
        {
            TempData["ErrorMessage"] = "Save changes was unsuccessful.";
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

InsuranceSystemProject/Views/PolicyProperty/PolicyPropertyCreate.cshtml
@model InsuranceSystemProject.Models.PolicyProperty

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PolicyProperty</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.Partial("PolicyPropertyEditForm")
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "PolicyPropertyIndex")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

InsuranceSystemProject/Views/PolicyProperty/PolicyPropertyEdit.cshtml
@model InsuranceSystemProject.Models.PolicyProperty

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PolicyProperty</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.Partial("PolicyPropertyEditForm")
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" class="btn btn-primary" value="Save" />
                <input type="button" class="btn btn-default" data-toggle="modal" data-target="#myModal" value="Delete" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "PolicyPropertyIndex")
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Warning !!</h4>
            </div>
            <div class="modal-body">
                Are you sure you want to delete this item ?
            </div>
            <div class="modal-footer">
                @using (Html.BeginForm("PolicyPropertyDelete", "PolicyProperty", new { id=Model.Id}))
                {
                    @Html.AntiForgeryToken()
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-warning">Delete</button>
                }
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

InsuranceSystemProject/Views/PolicyProperty/PolicyPropertyEditForm.cshtml
@model InsuranceSystemProject.Models.PolicyProperty

@if (Model != null && Model.Id != null)
{
    @Html.HiddenFor(model => model.Id)
}
else
{
        <div class="form-group">
            @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Id,"" , new { @class = "text-danger" })
            </div>
        </div>
}

        <div class="form-group">
            @Html.LabelFor(model => model.InsuranceValue, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.InsuranceValue, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.InsuranceValue,"" , new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, "City", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("City", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.City,"" , new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PolicyStartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PolicyStartDate, "Date")
                @Html.ValidationMessageFor(model => model.PolicyStartDate,"" , new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserId,"" , new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PersonId, "PersonId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PersonId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PersonId,"" , new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CompanyId, "CompanyId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CompanyId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CompanyId,"" , new { @class = "text-danger" })
            </div>
        </div>

InsuranceSystemProject/Views/PolicyProperty/PolicyPropertyIndex.cshtml
@model IEnumerable<InsuranceSystemProject.Models.PolicyProperty>

@{
    ViewBag.Title = "Index";
}
<style type='text/css'>
    /*設定 數字靠右*/
    td:nth-child(1n){text-align: right;}
    td:nth-child(2n){text-align: right;}
    td:nth-child(3n){text-align: right;}
    td:nth-child(6n){text-align: right;}
    td:nth-child(7n){text-align: right;}
</style>
<h2>Index</h2>
<h4>PolicyProperty</h4>
<p>
    @Html.ActionLink("Create New", "PolicyPropertyCreate")
</p>
<p>
    @using (Html.BeginForm("PolicyPropertyIndex", "PolicyProperty", FormMethod.Get))
    {
        <b>Search by:</b>
        @Html.RadioButton("searchBy", "Id")<text> Номер</text>
        @Html.RadioButton("searchBy", "Client")<text> Застрахован</text>
        @Html.RadioButton("searchBy", "Insurer")<text> Застраховател</text><br />
        @Html.TextBox("Search");<input type="submit" value="Search" />
    }
</p>
<table class="table">
    <tr>
        <th></th>
        <th>
            @Html.DisplayNameFor(model => model.InsuranceValue)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PolicyStartDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AspNetUser.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City1.CityName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.InsuranceCompany.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PersonDetail.FirstName)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink("Edit", "PolicyPropertyEdit", new { id=item.Id })
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.InsuranceValue)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PolicyStartDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AspNetUser.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.City1.CityName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.InsuranceCompany.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PersonDetail.FirstName)
        </td>

    </tr>
}

</table>