InsuranceSystemProject/Models/City.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceSystemProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.PersonDetails = new HashSet<PersonDetail>();
            this.PolicyAutoes = new HashSet<PolicyAuto>();
            this.PolicyKaskoes = new HashSet<PolicyKasko>();
            this.PolicyProperties = new HashSet<PolicyProperty>();
        }
    
        public int Id { get; set; }
        public string CityName { get; set; }
        public string PostCode { get; set; }
    
        public virtual ICollection<PersonDetail> PersonDetails { get; set; }
        public virtual ICollection<PolicyAuto> PolicyAutoes { get; set; }
        public virtual ICollection<PolicyKasko> PolicyKaskoes { get; set; }
        public virtual ICollection<PolicyProperty> PolicyProperties { get; set; }
    }
}

InsuranceSystemProject/Controllers/CityController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using InsuranceSystemProject.Models;

namespace InsuranceSystemProject.Controllers
{
    public class CityController : Controller
    {
        private Entities1 db = new Entities1();

        // GET: City/CityIndex
        public ActionResult CityIndex()
        {
            return View(db.Cities.ToList());
        }

        /*
        // GET: City/CityDetails/5
        public ActionResult CityDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            City city = db.Cities.Find(id);
            if (city == null)
            {
                return HttpNotFound();
            }
            return View(city);
        }
        */

        // GET: City/CityCreate
        public ActionResult CityCreate()
        {
            return View();
        }

        // POST: City/CityCreate
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CityCreate([Bind(Include = "Id,CityName,PostCode,PersonDetails,PolicyAutoes,PolicyKaskoes,PolicyProperties")] City city)
        {
            if (ModelState.IsValid)
            {
                db.Cities.Add(city);
                db.SaveChanges();
                DisplaySuccessMessage("Has append a City record");
                return RedirectToAction("CityIndex");
            }

            DisplayErrorMessage();
            return View(city);
        }

        // GET: City/CityEdit/5
        public ActionResult CityEdit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            City city = db.Cities.Find(id);
            if (city == null)
            {
                return HttpNotFound();
            }
            return View(city);
        }

        // POST: CityCity/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CityEdit([Bind(Include = "Id,CityName,PostCode,PersonDetails,PolicyAutoes,PolicyKaskoes,PolicyProperties")] City city)
        {
            if (ModelState.IsValid)
            {
                db.Entry(city).State = EntityState.Modified;
                db.SaveChanges();
                DisplaySuccessMessage("Has update a City record");
                return RedirectToAction("CityIndex");
            }
            DisplayErrorMessage();
            return View(city);
        }

        // GET: City/CityDelete/5
        public ActionResult CityDelete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            City city = db.Cities.Find(id);
            if (city == null)
            {
                return HttpNotFound();
            }
            return View(city);
        }

        // POST: City/CityDelete/5
        [HttpPost, ActionName("CityDelete")]
        [ValidateAntiForgeryToken]
        public ActionResult CityDeleteConfirmed(int id)
        {
            City city = db.Cities.Find(id);
            db.Cities.Remove(city);
            db.SaveChanges();
            DisplaySuccessMessage("Has delete a City record");
            return RedirectToAction("CityIndex");
        }

        private void DisplaySuccessMessage(string msgText)
        {
            TempData["SuccessMessage"] = msgText;
        }

        private void DisplayErrorMessage()
        {
            TempData["ErrorMessage"] = "Save changes was unsuccessful.";
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

InsuranceSystemProject/Views/City/CityCreate.cshtml
@model InsuranceSystemProject.Models.City

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>City</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.Partial("CityEditForm")
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "CityIndex")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

InsuranceSystemProject/Views/City/CityEdit.cshtml
@model InsuranceSystemProject.Models.City

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>City</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.Partial("CityEditForm")
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" class="btn btn-primary" value="Save" />
                <input type="button" class="btn btn-default" data-toggle="modal" data-target="#myModal" value="Delete" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "CityIndex")
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Warning !!</h4>
            </div>
            <div class="modal-body">
                Are you sure you want to delete this item ?
            </div>
            <div class="modal-footer">
                @using (Html.BeginForm("CityDelete", "City", new { id=Model.Id}))
                {
                    @Html.AntiForgeryToken()
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-warning">Delete</button>
                }
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

InsuranceSystemProject/Views/City/CityEditForm.cshtml
@model InsuranceSystemProject.Models.City

        <div class="form-group">
            @Html.LabelFor(model => model.CityName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CityName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CityName,"" , new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PostCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PostCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PostCode,"" , new { @class = "text-danger" })
            </div>
        </div>

InsuranceSystemProject/Views/City/CityIndex.cshtml
@model IEnumerable<InsuranceSystemProject.Models.City>

@{
    ViewBag.Title = "Index";
}
<style type='text/css'>
    /*設定 數字靠右*/
    td:nth-child(1n){text-align: right;}
</style>
<h2>Index</h2>
<h4>City</h4>
<p>
    @Html.ActionLink("Create New", "CityCreate")
</p>
<table class="table">
    <tr>
        <th></th>
        <th>
            @Html.DisplayNameFor(model => model.CityName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PostCode)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink("Edit", "CityEdit", new { id=item.Id })
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CityName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PostCode)
        </td>

    </tr>
}

</table>