InsuranceSystemProject/Models/Make.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceSystemProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Make
    {
        public Make()
        {
            this.PolicyAutoes = new HashSet<PolicyAuto>();
            this.PolicyKaskoes = new HashSet<PolicyKasko>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<PolicyAuto> PolicyAutoes { get; set; }
        public virtual ICollection<PolicyKasko> PolicyKaskoes { get; set; }
    }
}

InsuranceSystemProject/Controllers/MakeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using InsuranceSystemProject.Models;

namespace InsuranceSystemProject.Controllers
{
    public class MakeController : Controller
    {
        private Entities1 db = new Entities1();

        // GET: Make/MakeIndex
        public ActionResult MakeIndex()
        {
            return View(db.Makes.ToList());
        }

        /*
        // GET: Make/MakeDetails/5
        public ActionResult MakeDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Make make = db.Makes.Find(id);
            if (make == null)
            {
                return HttpNotFound();
            }
            return View(make);
        }
        */

        // GET: Make/MakeCreate
        public ActionResult MakeCreate()
        {
            return View();
        }

        // POST: Make/MakeCreate
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult MakeCreate([Bind(Include = "Id,Code,Title,PolicyAutoes,PolicyKaskoes")] Make make)
        {
            if (ModelState.IsValid)
            {
                db.Makes.Add(make);
                db.SaveChanges();
                DisplaySuccessMessage("Has append a Make record");
                return RedirectToAction("MakeIndex");
            }

            DisplayErrorMessage();
            return View(make);
        }

        // GET: Make/MakeEdit/5
        public ActionResult MakeEdit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Make make = db.Makes.Find(id);
            if (make == null)
            {
                return HttpNotFound();
            }
            return View(make);
        }

        // POST: MakeMake/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult MakeEdit([Bind(Include = "Id,Code,Title,PolicyAutoes,PolicyKaskoes")] Make make)
        {
            if (ModelState.IsValid)
            {
                db.Entry(make).State = EntityState.Modified;
                db.SaveChanges();
                DisplaySuccessMessage("Has update a Make record");
                return RedirectToAction("MakeIndex");
            }
            DisplayErrorMessage();
            return View(make);
        }

        // GET: Make/MakeDelete/5
        public ActionResult MakeDelete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Make make = db.Makes.Find(id);
            if (make == null)
            {
                return HttpNotFound();
            }
            return View(make);
        }

        // POST: Make/MakeDelete/5
        [HttpPost, ActionName("MakeDelete")]
        [ValidateAntiForgeryToken]
        public ActionResult MakeDeleteConfirmed(int id)
        {
            Make make = db.Makes.Find(id);
            db.Makes.Remove(make);
            db.SaveChanges();
            DisplaySuccessMessage("Has delete a Make record");
            return RedirectToAction("MakeIndex");
        }

        private void DisplaySuccessMessage(string msgText)
        {
            TempData["SuccessMessage"] = msgText;
        }

        private void DisplayErrorMessage()
        {
            TempData["ErrorMessage"] = "Save changes was unsuccessful.";
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

InsuranceSystemProject/Views/Make/MakeCreate.cshtml
@model InsuranceSystemProject.Models.Make

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Make</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.Partial("MakeEditForm")
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "MakeIndex")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

InsuranceSystemProject/Views/Make/MakeEdit.cshtml
@model InsuranceSystemProject.Models.Make

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Make</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.Partial("MakeEditForm")
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" class="btn btn-primary" value="Save" />
                <input type="button" class="btn btn-default" data-toggle="modal" data-target="#myModal" value="Delete" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "MakeIndex")
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Warning !!</h4>
            </div>
            <div class="modal-body">
                Are you sure you want to delete this item ?
            </div>
            <div class="modal-footer">
                @using (Html.BeginForm("MakeDelete", "Make", new { id=Model.Id}))
                {
                    @Html.AntiForgeryToken()
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-warning">Delete</button>
                }
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

InsuranceSystemProject/Views/Make/MakeEditForm.cshtml
@model InsuranceSystemProject.Models.Make

        <div class="form-group">
            @Html.LabelFor(model => model.Code, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Code,"" , new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title,"" , new { @class = "text-danger" })
            </div>
        </div>

InsuranceSystemProject/Views/Make/MakeIndex.cshtml
@model IEnumerable<InsuranceSystemProject.Models.Make>

@{
    ViewBag.Title = "Index";
}
<style type='text/css'>
    /*設定 數字靠右*/
    td:nth-child(1n){text-align: right;}
</style>
<h2>Index</h2>
<h4>Make</h4>
<p>
    @Html.ActionLink("Create New", "MakeCreate")
</p>
<table class="table">
    <tr>
        <th></th>
        <th>
            @Html.DisplayNameFor(model => model.Code)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink("Edit", "MakeEdit", new { id=item.Id })
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Code)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>

    </tr>
}

</table>