InsuranceSystemProject/Models/InsuranceCompany.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceSystemProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsuranceCompany
    {
        public InsuranceCompany()
        {
            this.PolicyAutoes = new HashSet<PolicyAuto>();
            this.PolicyKaskoes = new HashSet<PolicyKasko>();
            this.PolicyProperties = new HashSet<PolicyProperty>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> GoKoef { get; set; }
        public Nullable<decimal> TravelKoef { get; set; }
        public Nullable<decimal> AccidentKoef { get; set; }
        public Nullable<decimal> PropertyKoef { get; set; }
        public Nullable<decimal> KaskoKoef { get; set; }
        public Nullable<decimal> LifeKoef { get; set; }
        public Nullable<decimal> ResponsibilityKoef { get; set; }
    
        public virtual ICollection<PolicyAuto> PolicyAutoes { get; set; }
        public virtual ICollection<PolicyKasko> PolicyKaskoes { get; set; }
        public virtual ICollection<PolicyProperty> PolicyProperties { get; set; }
    }
}

InsuranceSystemProject/Controllers/InsuranceCompanyController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using InsuranceSystemProject.Models;

namespace InsuranceSystemProject.Controllers
{
    public class InsuranceCompanyController : Controller
    {
        private Entities1 db = new Entities1();

        // GET: InsuranceCompany/InsuranceCompanyIndex
        public ActionResult InsuranceCompanyIndex()
        {
            return View(db.InsuranceCompanies.ToList());
        }

        /*
        // GET: InsuranceCompany/InsuranceCompanyDetails/5
        public ActionResult InsuranceCompanyDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            InsuranceCompany insuranceCompany = db.InsuranceCompanies.Find(id);
            if (insuranceCompany == null)
            {
                return HttpNotFound();
            }
            return View(insuranceCompany);
        }
        */

        // GET: InsuranceCompany/InsuranceCompanyCreate
        public ActionResult InsuranceCompanyCreate()
        {
            return View();
        }

        // POST: InsuranceCompany/InsuranceCompanyCreate
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult InsuranceCompanyCreate([Bind(Include = "Id,Name,GoKoef,TravelKoef,AccidentKoef,PropertyKoef,KaskoKoef,LifeKoef,ResponsibilityKoef,PolicyAutoes,PolicyKaskoes,PolicyProperties")] InsuranceCompany insuranceCompany)
        {
            if (ModelState.IsValid)
            {
                db.InsuranceCompanies.Add(insuranceCompany);
                db.SaveChanges();
                DisplaySuccessMessage("Has append a InsuranceCompany record");
                return RedirectToAction("InsuranceCompanyIndex");
            }

            DisplayErrorMessage();
            return View(insuranceCompany);
        }

        // GET: InsuranceCompany/InsuranceCompanyEdit/5
        public ActionResult InsuranceCompanyEdit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            InsuranceCompany insuranceCompany = db.InsuranceCompanies.Find(id);
            if (insuranceCompany == null)
            {
                return HttpNotFound();
            }
            return View(insuranceCompany);
        }

        // POST: InsuranceCompanyInsuranceCompany/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult InsuranceCompanyEdit([Bind(Include = "Id,Name,GoKoef,TravelKoef,AccidentKoef,PropertyKoef,KaskoKoef,LifeKoef,ResponsibilityKoef,PolicyAutoes,PolicyKaskoes,PolicyProperties")] InsuranceCompany insuranceCompany)
        {
            if (ModelState.IsValid)
            {
                db.Entry(insuranceCompany).State = EntityState.Modified;
                db.SaveChanges();
                DisplaySuccessMessage("Has update a InsuranceCompany record");
                return RedirectToAction("InsuranceCompanyIndex");
            }
            DisplayErrorMessage();
            return View(insuranceCompany);
        }

        // GET: InsuranceCompany/InsuranceCompanyDelete/5
        public ActionResult InsuranceCompanyDelete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            InsuranceCompany insuranceCompany = db.InsuranceCompanies.Find(id);
            if (insuranceCompany == null)
            {
                return HttpNotFound();
            }
            return View(insuranceCompany);
        }

        // POST: InsuranceCompany/InsuranceCompanyDelete/5
        [HttpPost, ActionName("InsuranceCompanyDelete")]
        [ValidateAntiForgeryToken]
        public ActionResult InsuranceCompanyDeleteConfirmed(int id)
        {
            InsuranceCompany insuranceCompany = db.InsuranceCompanies.Find(id);
            db.InsuranceCompanies.Remove(insuranceCompany);
            db.SaveChanges();
            DisplaySuccessMessage("Has delete a InsuranceCompany record");
            return RedirectToAction("InsuranceCompanyIndex");
        }

        private void DisplaySuccessMessage(string msgText)
        {
            TempData["SuccessMessage"] = msgText;
        }

        private void DisplayErrorMessage()
        {
            TempData["ErrorMessage"] = "Save changes was unsuccessful.";
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

InsuranceSystemProject/Views/InsuranceCompany/InsuranceCompanyCreate.cshtml
@model InsuranceSystemProject.Models.InsuranceCompany

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>InsuranceCompany</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.Partial("InsuranceCompanyEditForm")
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "InsuranceCompanyIndex")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

InsuranceSystemProject/Views/InsuranceCompany/InsuranceCompanyEdit.cshtml
@model InsuranceSystemProject.Models.InsuranceCompany

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>InsuranceCompany</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.Partial("InsuranceCompanyEditForm")
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" class="btn btn-primary" value="Save" />
                <input type="button" class="btn btn-default" data-toggle="modal" data-target="#myModal" value="Delete" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "InsuranceCompanyIndex")
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Warning !!</h4>
            </div>
            <div class="modal-body">
                Are you sure you want to delete this item ?
            </div>
            <div class="modal-footer">
                @using (Html.BeginForm("InsuranceCompanyDelete", "InsuranceCompany", new { id=Model.Id}))
                {
                    @Html.AntiForgeryToken()
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-warning">Delete</button>
                }
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

InsuranceSystemProject/Views/InsuranceCompany/InsuranceCompanyEditForm.cshtml
@model InsuranceSystemProject.Models.InsuranceCompany

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name,"" , new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GoKoef, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GoKoef, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GoKoef,"" , new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TravelKoef, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TravelKoef, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TravelKoef,"" , new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AccidentKoef, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AccidentKoef, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AccidentKoef,"" , new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PropertyKoef, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PropertyKoef, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PropertyKoef,"" , new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.KaskoKoef, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.KaskoKoef, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.KaskoKoef,"" , new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LifeKoef, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LifeKoef, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LifeKoef,"" , new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ResponsibilityKoef, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ResponsibilityKoef, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ResponsibilityKoef,"" , new { @class = "text-danger" })
            </div>
        </div>

InsuranceSystemProject/Views/InsuranceCompany/InsuranceCompanyIndex.cshtml
@model IEnumerable<InsuranceSystemProject.Models.InsuranceCompany>

@{
    ViewBag.Title = "Index";
}
<style type='text/css'>
    /*設定 數字靠右*/
    td:nth-child(1n){text-align: right;}
    td:nth-child(3n){text-align: right;}
    td:nth-child(4n){text-align: right;}
    td:nth-child(5n){text-align: right;}
    td:nth-child(6n){text-align: right;}
    td:nth-child(7n){text-align: right;}
    td:nth-child(8n){text-align: right;}
    td:nth-child(9n){text-align: right;}
</style>
<h2>Index</h2>
<h4>InsuranceCompany</h4>
<p>
    @Html.ActionLink("Create New", "InsuranceCompanyCreate")
</p>
<table class="table">
    <tr>
        <th></th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.GoKoef)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TravelKoef)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AccidentKoef)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PropertyKoef)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.KaskoKoef)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LifeKoef)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ResponsibilityKoef)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink("Edit", "InsuranceCompanyEdit", new { id=item.Id })
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.GoKoef)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TravelKoef)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AccidentKoef)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PropertyKoef)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.KaskoKoef)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LifeKoef)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ResponsibilityKoef)
        </td>

    </tr>
}

</table>